// <auto-generated />
using System;
using GreenVendor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenVendor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626204606_SeedQuestions")]
    partial class SeedQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenVendor.Domain.Entities.BuyerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredMinGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BuyerProfiles");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.EsgScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Environmental")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Governance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Social")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EsgScores");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\", \"Points\":0}, {\"Text\":\"Partially (up to 30%)\", \"Points\":0.5}, {\"Text\":\"Yes (more than 30%)\", \"Points\": 1.0}]",
                            Text = "Does your company use renewable energy sources (RES)?",
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\", \"Points\":0}, {\"Text\":\"In the production process\", \"Points\":0.3}, {\"Text\":\"Yes it works completely\", \"Points\": 1.0}]",
                            Text = "Has the company implemented a system for the separate collection and safe disposal of hazardous waste?",
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\",\"Points\":0},{\"Text\":\"Accounting is maintained, but auditing is not carried out\",\"Points\":0.5},{\"Text\":\"Yes, the data is certified by an external auditor\",\"Points\":1.0}]",
                            Text = "Does your company regularly record and audit its greenhouse gas (CO2) emissions?",
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\",\"Points\":0},{\"Text\":\"Yes, in some areas\",\"Points\":0.6},{\"Text\":\"Yes, in all production\",\"Points\":1.0}]",
                            Text = "Does the company use closed-loop water supply technologies?",
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"There are no basic regulations\",\"Points\":0},{\"Text\":\"There are basic instructions\",\"Points\":0.5},{\"Text\":\"Yes, international standards (ISO 45001) have been implemented\",\"Points\":1.0}]",
                            Text = "Does the company have formal occupational safety and health and injury reduction programs?",
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No, employees train themselves.\",\"Points\":0},{\"Text\":\"Yes, for some departments\",\"Points\":0.5},{\"Text\":\"Yes, systematically for all staff\",\"Points\":1.0}]",
                            Text = "Does the company provide regular training, workshops, or advanced training courses for employees at its own expense?",
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\",\"Points\":0},{\"Text\":\"Declared orally\",\"Points\":0.4},{\"Text\":\"Yes, it is enshrined in the Company Code\",\"Points\":1.0}]",
                            Text = "Does the company have a formal equality, inclusion and non-discrimination policy?",
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\",\"Points\":0},{\"Text\":\"Rarely / one-time promotions\",\"Points\":0.5},{\"Text\":\"Yes, on a regular long-term basis\",\"Points\":1.0}]",
                            Text = "Does the company finance charitable, environmental, or social projects in the regions where it operates?",
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No\",\"Points\":0},{\"Text\":\"There are only general rules in contracts\",\"Points\":0.4},{\"Text\":\"Yes, there is a dedicated compliance officer and regulations.\",\"Points\":1.0}]",
                            Text = "Has the company adopted a Code of Business Ethics and an anti-corruption compliance policy?",
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No, only government audits\",\"Points\":0},{\"Text\":\"Once every few years\",\"Points\":0.5},{\"Text\":\"Yes, annually by independent auditors\",\"Points\":1.0}]",
                            Text = "Are your company's financial statements regularly audited by an independent external auditor?",
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"No channels\",\"Points\":0},{\"Text\":\"There is a regular suggestion box (does not guarantee anonymity)\",\"Points\":0.4},{\"Text\":\"Yes, there is a dedicated hotline / anonymous portal\",\"Points\":1.0}]",
                            Text = "Does the company have transparent and secure channels for anonymous whistleblowing?",
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            IsActive = true,
                            OptionsJson = "[{\"Text\":\"Information is completely closed\",\"Points\":0},{\"Text\":\"Partially disclosed upon request\",\"Points\":0.6},{\"Text\":\"Yes, the information is completely public and transparent\",\"Points\":1.0}]",
                            Text = "Does the company disclose the structure of its ultimate beneficial owners and top management on its official website?",
                            Weight = 0.7m
                        });
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.SupplierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LatestScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LatestScoreId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SupplierProfiles");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuestionnaireAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PointsEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireAnswers");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.BuyerProfile", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.User", "User")
                        .WithOne("BuyerProfile")
                        .HasForeignKey("GreenVendor.Domain.Entities.BuyerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Order", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.BuyerProfile", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenVendor.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Product", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Questionnaire", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.EsgScore", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId");

                    b.HasOne("GreenVendor.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.SupplierProfile", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.EsgScore", "LatestScore")
                        .WithMany()
                        .HasForeignKey("LatestScoreId");

                    b.HasOne("GreenVendor.Domain.Entities.User", "User")
                        .WithOne("SupplierProfile")
                        .HasForeignKey("GreenVendor.Domain.Entities.SupplierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LatestScore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionnaireAnswer", b =>
                {
                    b.HasOne("GreenVendor.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenVendor.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.BuyerProfile", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.Questionnaire", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.SupplierProfile", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GreenVendor.Domain.Entities.User", b =>
                {
                    b.Navigation("BuyerProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SupplierProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
